import { Property } from './types';
import apartmentImg from '@/assets/property-apartment.jpg';
import apartmentImg2 from '@/assets/property-apartment-2.jpg';
import apartmentImg3 from '@/assets/property-apartment-3.jpg';
import houseImg from '@/assets/property-house.jpg';
import houseImg2 from '@/assets/property-house-2.jpg';
import houseImg3 from '@/assets/property-house-3.jpg';
import villaImg from '@/assets/property-villa.jpg';
import villaImg2 from '@/assets/property-villa-2.jpg';
import villaImg3 from '@/assets/property-villa-3.jpg';
import shopImg from '@/assets/property-shop.jpg';
import shopImg2 from '@/assets/property-shop-2.jpg';
import plotImg from '@/assets/property-plot.jpg';
import plotImg2 from '@/assets/property-plot-2.jpg';
import buildingImg from '@/assets/property-building.jpg';
import buildingImg2 from '@/assets/property-building-2.jpg';

const imageVariants: Record<string, string[]> = {
  apartment: [apartmentImg, apartmentImg2, apartmentImg3],
  house: [houseImg, houseImg2, houseImg3],
  villa: [villaImg, villaImg2, villaImg3],
  shop: [shopImg, shopImg2],
  plot: [plotImg, plotImg2],
  building: [buildingImg, buildingImg2],
};

const getImage = (type: string, index: number): string => {
  const variants = imageVariants[type] || [apartmentImg];
  return variants[index % variants.length];
};

export const properties: Property[] = [
  {
    id: '1',
    title: 'Luxurious 3BHK Apartment in Bandra West',
    description: 'Spacious 3BHK apartment with sea-facing balcony, modular kitchen, and premium fittings. Located in the heart of Bandra West with easy access to Linking Road and Bandstand Promenade. Gated community with 24/7 security, swimming pool, and gymnasium.',
    price: 32500000,
    location: 'Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    size: '1,850 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 3,
    bathrooms: 2,
    image: getImage("apartment", 0),
    agentName: 'Rajesh Sharma',
    agentPhone: '+91 98765 43210',
    createdAt: '2026-02-15',
    features: ['Sea View', 'Modular Kitchen', 'Swimming Pool', 'Gym', '24/7 Security', 'Parking'],
  },
  {
    id: '2',
    title: 'Independent House with Garden in Vasant Kunj',
    description: 'Beautiful independent house with a spacious garden, 4 bedrooms, servant quarter, and a private driveway. Located in the upscale Vasant Kunj area of South Delhi, close to malls and metro station.',
    price: 45000000,
    location: 'Vasant Kunj',
    city: 'New Delhi',
    state: 'Delhi',
    size: '3,200 sq.ft.',
    type: 'house',
    status: 'available',
    bedrooms: 4,
    bathrooms: 3,
    image: getImage("house", 0),
    agentName: 'Priya Mehta',
    agentPhone: '+91 99887 65432',
    createdAt: '2026-01-20',
    features: ['Garden', 'Servant Quarter', 'Parking', 'Modular Kitchen', 'Power Backup'],
  },
  {
    id: '3',
    title: 'Premium Villa with Pool in Candolim',
    description: 'Stunning 5-bedroom luxury villa with private swimming pool, landscaped garden, and rooftop terrace. Minutes from Candolim Beach. Fully furnished with premium Italian marble flooring and smart home automation.',
    price: 85000000,
    location: 'Candolim',
    city: 'North Goa',
    state: 'Goa',
    size: '5,500 sq.ft.',
    type: 'villa',
    status: 'available',
    bedrooms: 5,
    bathrooms: 5,
    image: getImage("villa", 0),
    agentName: 'Vikram Desai',
    agentPhone: '+91 97654 32109',
    createdAt: '2026-03-01',
    features: ['Swimming Pool', 'Beach Nearby', 'Smart Home', 'Rooftop Terrace', 'Furnished', 'Italian Marble'],
  },
  {
    id: '4',
    title: 'Commercial Shop in MG Road',
    description: 'Prime commercial shop space on the bustling MG Road, Bangalore. Ground floor with large glass frontage, ideal for retail, showroom, or restaurant. High footfall area with excellent connectivity.',
    price: 18000000,
    location: 'MG Road',
    city: 'Bangalore',
    state: 'Karnataka',
    size: '1,200 sq.ft.',
    type: 'shop',
    status: 'available',
    image: getImage("shop", 0),
    agentName: 'Ananya Reddy',
    agentPhone: '+91 96543 21098',
    createdAt: '2026-02-28',
    features: ['Ground Floor', 'Glass Frontage', 'High Footfall', 'Parking', 'Power Backup'],
  },
  {
    id: '5',
    title: 'Residential Plot in Hinjewadi',
    description: 'RERA approved residential plot in Hinjewadi Phase 3, Pune. Close to IT parks, schools, and hospitals. Clear title, ready for construction. Excellent investment opportunity in a rapidly developing area.',
    price: 8500000,
    location: 'Hinjewadi Phase 3',
    city: 'Pune',
    state: 'Maharashtra',
    size: '2,400 sq.ft.',
    type: 'plot',
    status: 'available',
    image: getImage("plot", 0),
    agentName: 'Amit Kulkarni',
    agentPhone: '+91 95432 10987',
    createdAt: '2026-03-05',
    features: ['RERA Approved', 'Clear Title', 'Near IT Parks', 'Road Facing', 'Water Supply'],
  },
  {
    id: '6',
    title: 'Commercial Building in HITEC City',
    description: 'Modern commercial building with 6 floors of office space in HITEC City, Hyderabad. Grade A construction with central air conditioning, high-speed elevators, and ample parking. Ideal for IT companies.',
    price: 250000000,
    location: 'HITEC City',
    city: 'Hyderabad',
    state: 'Telangana',
    size: '25,000 sq.ft.',
    type: 'building',
    status: 'available',
    image: getImage("building", 0),
    agentName: 'Srinivas Rao',
    agentPhone: '+91 94321 09876',
    createdAt: '2026-01-10',
    features: ['Central AC', 'High-Speed Elevators', 'Parking', 'Power Backup', 'Fire Safety', 'CCTV'],
  },
  {
    id: '7',
    title: 'Cozy 2BHK Flat in Koramangala',
    description: 'Well-maintained 2BHK apartment in the vibrant Koramangala neighbourhood. Walking distance to restaurants, cafes, and Forum Mall. Semi-furnished with wardrobes and split ACs.',
    price: 9500000,
    location: 'Koramangala',
    city: 'Bangalore',
    state: 'Karnataka',
    size: '1,100 sq.ft.',
    type: 'apartment',
    status: 'rented',
    bedrooms: 2,
    bathrooms: 2,
    image: getImage("apartment", 1),
    agentName: 'Ananya Reddy',
    agentPhone: '+91 96543 21098',
    createdAt: '2026-02-10',
    features: ['Semi-Furnished', 'Split AC', 'Wardrobes', 'Near Mall', 'Gym'],
  },
  {
    id: '8',
    title: 'Farmhouse on NH-8 Highway',
    description: 'Sprawling farmhouse with fruit orchards, swimming pool, and party lawn on NH-8 Highway near Jaipur. Perfect weekend retreat. Includes a caretaker cottage and bore well.',
    price: 35000000,
    location: 'NH-8 Highway',
    city: 'Jaipur',
    state: 'Rajasthan',
    size: '10,000 sq.ft.',
    type: 'house',
    status: 'sold',
    bedrooms: 6,
    bathrooms: 4,
    image: getImage("house", 1),
    agentName: 'Manish Singh',
    agentPhone: '+91 93210 98765',
    createdAt: '2025-12-20',
    features: ['Fruit Orchard', 'Swimming Pool', 'Party Lawn', 'Bore Well', 'Caretaker Cottage'],
  },
  {
    id: '9',
    title: 'Corner Shop in Connaught Place',
    description: 'Premium corner shop in the iconic Connaught Place, New Delhi. Double-height ceiling with mezzanine floor. High visibility location suitable for luxury retail brands.',
    price: 75000000,
    location: 'Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    size: '800 sq.ft.',
    type: 'shop',
    status: 'available',
    image: getImage("shop", 1),
    agentName: 'Priya Mehta',
    agentPhone: '+91 99887 65432',
    createdAt: '2026-03-08',
    features: ['Corner Location', 'Double Height', 'Mezzanine', 'Prime Location', 'Metro Nearby'],
  },
  {
    id: '10',
    title: 'Sea-Facing Plot in ECR',
    description: 'Exclusive sea-facing plot on East Coast Road, Chennai. Ideal for building a beach house or resort. DTCP approved with clear patta. One of the last available sea-facing plots in the area.',
    price: 22000000,
    location: 'East Coast Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    size: '4,000 sq.ft.',
    type: 'plot',
    status: 'available',
    image: getImage("plot", 1),
    agentName: 'Karthik Iyer',
    agentPhone: '+91 92109 87654',
    createdAt: '2026-02-25',
    features: ['Sea Facing', 'DTCP Approved', 'Clear Title', 'Road Access', 'Beach View'],
  },
  {
    id: '11',
    title: 'Penthouse in Salt Lake City',
    description: 'Luxurious duplex penthouse in Salt Lake Sector V, Kolkata. Panoramic city views, private terrace garden, jacuzzi, and home theatre. Premium gated community with clubhouse.',
    price: 42000000,
    location: 'Salt Lake Sector V',
    city: 'Kolkata',
    state: 'West Bengal',
    size: '4,200 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 4,
    bathrooms: 4,
    image: getImage("apartment", 2),
    agentName: 'Sourav Banerjee',
    agentPhone: '+91 91098 76543',
    createdAt: '2026-03-02',
    features: ['Duplex', 'Terrace Garden', 'Jacuzzi', 'Home Theatre', 'City View', 'Clubhouse'],
  },
  {
    id: '12',
    title: 'Luxury Villa in Whitefield',
    description: 'Elegant 4BHK villa in a premium gated community in Whitefield, Bangalore. Italian marble flooring, modular kitchen, home automation, and private garden. Close to ITPL and international schools.',
    price: 55000000,
    location: 'Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    size: '3,800 sq.ft.',
    type: 'villa',
    status: 'available',
    bedrooms: 4,
    bathrooms: 4,
    image: getImage("villa", 1),
    agentName: 'Ananya Reddy',
    agentPhone: '+91 96543 21098',
    createdAt: '2026-02-18',
    features: ['Gated Community', 'Home Automation', 'Italian Marble', 'Garden', 'Near Schools', 'Clubhouse'],
  },
  {
    id: '13',
    title: '3BHK Luxury Flat in Sector 65, Gurugram',
    description: 'Premium 3BHK apartment in a top-rated society in Sector 65, Gurugram. Close to Golf Course Extension Road, cyber hubs, and international schools. Clubhouse, rooftop infinity pool, and landscaped gardens.',
    price: 18500000,
    location: 'Sector 65',
    city: 'Gurugram',
    state: 'Haryana',
    size: '1,950 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 3,
    bathrooms: 3,
    image: getImage("apartment", 3),
    agentName: 'Deepak Yadav',
    agentPhone: '+91 98100 12345',
    createdAt: '2026-03-06',
    features: ['Infinity Pool', 'Clubhouse', 'Near Cyber Hub', 'Power Backup', 'Covered Parking', 'Gym'],
  },
  {
    id: '14',
    title: 'Independent Villa on Sohna Road',
    description: 'Spacious 4BHK independent villa on Sohna Road with private garden, terrace, and car porch. Gated township with 24/7 security, clubhouse, and sports facilities. 15 mins from Rajiv Chowk.',
    price: 27500000,
    location: 'Sohna Road',
    city: 'Gurugram',
    state: 'Haryana',
    size: '3,500 sq.ft.',
    type: 'villa',
    status: 'available',
    bedrooms: 4,
    bathrooms: 4,
    image: getImage("villa", 2),
    agentName: 'Deepak Yadav',
    agentPhone: '+91 98100 12345',
    createdAt: '2026-02-22',
    features: ['Private Garden', 'Car Porch', 'Gated Township', '24/7 Security', 'Clubhouse', 'Sports Facilities'],
  },
  {
    id: '15',
    title: 'Residential Plot in Sohna',
    description: 'DTCP approved residential plot in Sohna, Haryana. Located near the upcoming KMP Expressway and Sohna Elevated Road. Excellent investment opportunity in Gurugram\'s fastest growing corridor.',
    price: 6500000,
    location: 'Sohna',
    city: 'Sohna',
    state: 'Haryana',
    size: '1,800 sq.ft.',
    type: 'plot',
    status: 'available',
    image: getImage("plot", 2),
    agentName: 'Rakesh Tanwar',
    agentPhone: '+91 99100 54321',
    createdAt: '2026-03-04',
    features: ['DTCP Approved', 'Near KMP Expressway', 'Clear Title', 'Boundary Wall', 'Water Supply', 'Road Facing'],
  },
  {
    id: '16',
    title: 'Commercial Shop in Sector 29, Gurugram',
    description: 'Prime commercial shop in the bustling Sector 29 market, Gurugram. Ground floor with wide frontage, ideal for restaurant, café, or retail outlet. High footfall area near Leisure Valley and Huda City Centre Metro.',
    price: 22000000,
    location: 'Sector 29',
    city: 'Gurugram',
    state: 'Haryana',
    size: '900 sq.ft.',
    type: 'shop',
    status: 'available',
    image: getImage("shop", 2),
    agentName: 'Rakesh Tanwar',
    agentPhone: '+91 99100 54321',
    createdAt: '2026-03-07',
    features: ['Ground Floor', 'Wide Frontage', 'High Footfall', 'Near Metro', 'Parking', 'Power Backup'],
  },
  {
    id: '17',
    title: '4BHK Floor in DLF Phase 2, Gurugram',
    description: 'Beautifully designed 4BHK independent floor in DLF Phase 2. Italian marble, modular kitchen, spacious balconies, and servant quarter. Walking distance to DLF Cyber City and Galleria Market.',
    price: 35000000,
    location: 'DLF Phase 2',
    city: 'Gurugram',
    state: 'Haryana',
    size: '2,800 sq.ft.',
    type: 'house',
    status: 'available',
    bedrooms: 4,
    bathrooms: 3,
    image: getImage("house", 2),
    agentName: 'Deepak Yadav',
    agentPhone: '+91 98100 12345',
    createdAt: '2026-02-28',
    features: ['Italian Marble', 'Modular Kitchen', 'Servant Quarter', 'Near Cyber City', 'Park Facing', 'Covered Parking'],
  },
  {
    id: '18',
    title: 'Farmhouse Plot near Sohna',
    description: 'Premium farmhouse plot on Sohna-Palwal Road surrounded by Aravalli hills. Ideal for weekend retreat or farmhouse construction. Bore well, electricity connection, and approach road available.',
    price: 12000000,
    location: 'Sohna-Palwal Road',
    city: 'Sohna',
    state: 'Haryana',
    size: '5,000 sq.ft.',
    type: 'plot',
    status: 'available',
    image: getImage("plot", 3),
    agentName: 'Rakesh Tanwar',
    agentPhone: '+91 99100 54321',
    createdAt: '2026-03-01',
    features: ['Aravalli View', 'Bore Well', 'Electricity', 'Approach Road', 'Boundary Wall', 'Clear Title'],
  },
  {
    id: '19',
    title: '2BHK Flat in Noida Sector 150',
    description: 'Modern 2BHK apartment in a premium high-rise in Sector 150, Noida. Close to Noida-Greater Noida Expressway and upcoming Jewar Airport. Pool, clubhouse, and jogging track.',
    price: 7200000,
    location: 'Sector 150',
    city: 'Noida',
    state: 'Uttar Pradesh',
    size: '1,050 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 2,
    bathrooms: 2,
    image: getImage("apartment", 4),
    agentName: 'Neha Gupta',
    agentPhone: '+91 98765 11223',
    createdAt: '2026-03-08',
    features: ['Swimming Pool', 'Clubhouse', 'Jogging Track', 'Near Expressway', 'Power Backup', 'Lift'],
  },
  {
    id: '20',
    title: 'Heritage Haveli in Udaipur',
    description: 'Restored heritage haveli near Lake Pichola, Udaipur. 8 rooms with courtyard, rooftop, and lake views. Ideal for boutique hotel or luxury residence.',
    price: 95000000,
    location: 'Near Lake Pichola',
    city: 'Udaipur',
    state: 'Rajasthan',
    size: '8,000 sq.ft.',
    type: 'house',
    status: 'available',
    bedrooms: 8,
    bathrooms: 6,
    image: getImage("house", 3),
    agentName: 'Manish Singh',
    agentPhone: '+91 93210 98765',
    createdAt: '2026-02-12',
    features: ['Lake View', 'Heritage Property', 'Courtyard', 'Rooftop', 'Restored', 'Tourist Zone'],
  },
  {
    id: '21',
    title: '3BHK on Dwarka Expressway, Gurugram',
    description: 'Brand new 3BHK flat on Dwarka Expressway. Vastu compliant, modular kitchen, large balconies with green views. 5 mins from upcoming metro station.',
    price: 14500000,
    location: 'Dwarka Expressway',
    city: 'Gurugram',
    state: 'Haryana',
    size: '1,700 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 3,
    bathrooms: 2,
    image: getImage("apartment", 5),
    agentName: 'Deepak Yadav',
    agentPhone: '+91 98100 12345',
    createdAt: '2026-03-09',
    features: ['Vastu Compliant', 'Modular Kitchen', 'Green View', 'Near Metro', 'Clubhouse', 'Kids Play Area'],
  },
  {
    id: '22',
    title: 'Waterfront Villa in Kochi',
    description: 'Stunning 4BHK waterfront villa in Maradu, Kochi. Private boat jetty, infinity pool, and tropical garden. Kerala traditional architecture with modern interiors.',
    price: 62000000,
    location: 'Maradu',
    city: 'Kochi',
    state: 'Kerala',
    size: '4,500 sq.ft.',
    type: 'villa',
    status: 'available',
    bedrooms: 4,
    bathrooms: 4,
    image: getImage("villa", 3),
    agentName: 'Thomas Kurian',
    agentPhone: '+91 94567 88901',
    createdAt: '2026-02-20',
    features: ['Waterfront', 'Boat Jetty', 'Infinity Pool', 'Tropical Garden', 'Traditional Architecture', 'Furnished'],
  },
  {
    id: '23',
    title: 'Office Space in BKC, Mumbai',
    description: 'Plug-and-play office in Bandra Kurla Complex. Fully furnished with workstations, cabins, and conference room. Grade A building with 24/7 access.',
    price: 48000000,
    location: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    size: '2,200 sq.ft.',
    type: 'building',
    status: 'available',
    image: getImage("building", 1),
    agentName: 'Rajesh Sharma',
    agentPhone: '+91 98765 43210',
    createdAt: '2026-03-03',
    features: ['Plug & Play', 'Furnished', 'Conference Room', '24/7 Access', 'Metro Nearby', 'Cafeteria'],
  },
  {
    id: '24',
    title: 'Agricultural Land in Karnal',
    description: 'Fertile agricultural land on GT Road near Karnal, Haryana. Tube well, electricity, and canal water available. Falls under upcoming industrial corridor.',
    price: 15000000,
    location: 'GT Road',
    city: 'Karnal',
    state: 'Haryana',
    size: '1 Acre',
    type: 'plot',
    status: 'available',
    image: getImage("plot", 4),
    agentName: 'Rakesh Tanwar',
    agentPhone: '+91 99100 54321',
    createdAt: '2026-02-14',
    features: ['Tube Well', 'Canal Water', 'Electricity', 'GT Road Access', 'Fertile Land', 'Clear Title'],
  },
  {
    id: '25',
    title: 'Penthouse in Chandigarh',
    description: 'Exclusive 4BHK penthouse in Zirakpur. Rooftop terrace with Shivalik hills view. Private elevator, home theatre, and designer interiors. Near Chandigarh Airport.',
    price: 38000000,
    location: 'Zirakpur',
    city: 'Chandigarh',
    state: 'Punjab',
    size: '3,600 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 4,
    bathrooms: 4,
    image: getImage("apartment", 6),
    agentName: 'Gurpreet Kaur',
    agentPhone: '+91 98765 99887',
    createdAt: '2026-03-05',
    features: ['Penthouse', 'Hills View', 'Private Elevator', 'Home Theatre', 'Rooftop Terrace', 'Near Airport'],
  },
  {
    id: '26',
    title: 'Shop in Lucknow Hazratganj',
    description: 'Premium retail shop in Hazratganj market, Lucknow. Ground floor corner unit with excellent visibility. Surrounded by branded showrooms and heritage buildings.',
    price: 28000000,
    location: 'Hazratganj',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    size: '650 sq.ft.',
    type: 'shop',
    status: 'available',
    image: getImage("shop", 3),
    agentName: 'Neha Gupta',
    agentPhone: '+91 98765 11223',
    createdAt: '2026-02-26',
    features: ['Corner Unit', 'Ground Floor', 'Heritage Area', 'High Footfall', 'Branded Market', 'Parking'],
  },
  {
    id: '27',
    title: '3BHK on SG Highway, Ahmedabad',
    description: 'Spacious 3BHK on SG Highway, Ahmedabad. Society with cricket pitch, meditation zone, and co-working space. Near ISCON Mega Mall and IIM Ahmedabad.',
    price: 11000000,
    location: 'SG Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
    size: '1,800 sq.ft.',
    type: 'apartment',
    status: 'available',
    bedrooms: 3,
    bathrooms: 2,
    image: getImage("apartment", 7),
    agentName: 'Harsh Patel',
    agentPhone: '+91 97654 00112',
    createdAt: '2026-03-07',
    features: ['Cricket Pitch', 'Co-Working', 'Meditation Zone', 'Near Mall', 'Gym', 'Covered Parking'],
  },
  {
    id: '28',
    title: 'Row House in Faridabad',
    description: 'Modern 3BHK row house in Sector 88, Faridabad. Gated community with parks, community hall, and 24/7 water. 10 mins from Delhi border.',
    price: 9800000,
    location: 'Sector 88',
    city: 'Faridabad',
    state: 'Haryana',
    size: '1,600 sq.ft.',
    type: 'house',
    status: 'available',
    bedrooms: 3,
    bathrooms: 2,
    image: getImage("house", 4),
    agentName: 'Rakesh Tanwar',
    agentPhone: '+91 99100 54321',
    createdAt: '2026-03-10',
    features: ['Gated Community', 'Park Facing', '24/7 Water', 'Near Railway', 'Community Hall', 'Vastu Compliant'],
  },
  {
    id: '29',
    title: 'Beach Plot in Alibaug',
    description: 'Beach-facing plot in Alibaug, 20 mins ferry from Mumbai. CIDCO approved, ideal for beach villa or resort. Coconut groves with direct beach access.',
    price: 32000000,
    location: 'Alibaug Beach',
    city: 'Alibaug',
    state: 'Maharashtra',
    size: '5,000 sq.ft.',
    type: 'plot',
    status: 'available',
    image: getImage("plot", 5),
    agentName: 'Rajesh Sharma',
    agentPhone: '+91 98765 43210',
    createdAt: '2026-02-18',
    features: ['Beach Facing', 'CIDCO Approved', 'Coconut Groves', 'Ferry Access', 'Clear Title', 'Road Access'],
  },
  {
    id: '30',
    title: 'IT Park Floor in Indore',
    description: 'Full floor office in Crystal IT Park, Indore. 50 workstations, server room, pantry, reception. Central AC with DG backup. Near Vijay Nagar hub.',
    price: 35000000,
    location: 'Crystal IT Park',
    city: 'Indore',
    state: 'Madhya Pradesh',
    size: '5,500 sq.ft.',
    type: 'building',
    status: 'available',
    image: getImage("building", 2),
    agentName: 'Harsh Patel',
    agentPhone: '+91 97654 00112',
    createdAt: '2026-03-02',
    features: ['Full Floor', 'Server Room', 'Central AC', 'DG Backup', '50 Workstations', 'Reception'],
  },
];

export const formatPrice = (price: number): string => {
  if (price >= 10000000) {
    return `₹${(price / 10000000).toFixed(2)} Cr`;
  } else if (price >= 100000) {
    return `₹${(price / 100000).toFixed(2)} L`;
  }
  return `₹${price.toLocaleString('en-IN')}`;
};

export const propertyTypeLabels: Record<string, string> = {
  house: 'House',
  apartment: 'Apartment',
  plot: 'Plot',
  shop: 'Shop',
  building: 'Building',
  villa: 'Villa',
};

export const cities = [...new Set(properties.map(p => p.city))];
export const states = [...new Set(properties.map(p => p.state))];
